//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.19 at 11:23:54 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.gb.ru/lesson4_hw/webservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.gb.lesson4_hw.webservice;
